nodelist {
    node {
        ring0_addr: 192.168.56.11
        name: node11
        nodeid: 1
    }
    node {
        ring0_addr: 192.168.56.12
        name: node12
        nodeid: 2
    }
    node {
        ring0_addr: 192.168.56.13
        name: node13
        nodeid: 3
    }
}